spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/runeat
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: ture

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸

jwt:
  secret:
    key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

google:
  clientId: 213617031580-3bjijd93fo1fh4jekjo088s6qbb6p6rt.apps.googleusercontent.com
